### ISSUE TITLE
 No module named zope.interface

### ISSUE THREAD

**Issue by breconbeacons** [geodrinx/gearthview#1]
During installation an error loading plugin message appears "The plugin is broken. Python said: No module named zope.interface"

QGIS Version 2.6.1

**Comment by geodrinx** [comment]
Install the following python libraries: 

twisted\            Twisted-13.0.0-py2.7-win32  
                 ( https://pypi.python.org/pypi/Twisted/13.0.0  )

zope\               zope.interface-3.6.0-py2.7-win32  
                 ( https://pypi.python.org/pypi/zope.interface/3.6.0 )

**Comment by Andre-J** [comment]
The page for zope.interface only serves a package for Python 2.6. Is it save to use zope.interface-3.6.7 or newer versions? Current is 4.1.2

**Comment by rgisset** [comment]
On Windows, you need to copy   

zope 
twisted

inside the QGIS  path.   For example:

QGIS Brighton\apps\Python27\Lib\site-packages\twisted\
QGIS Brighton\apps\Python27\Lib\site-packages\zope\

**Comment by PedroVenancio** [comment]
Hi,

I installed zope.interface-3.6.7.win-amd64-py2.7.exe, because there is no version 3.6.0 for Python 2.7, but it keeps showing "No module named zope.interface".

I've also tried to copy to the Python folder within OSGeo4W, but without success.

**Comment by rgisset** [comment]
You need to install (that is copy the dirs "zope"  and   "twisted") inside 

QGIS Brighton\apps\Python27\Lib\site-packages\twisted\
QGIS Brighton\apps\Python27\Lib\site-packages\zope\

**Comment by QGIS-user** [comment]
Hello
Something is not clear for me:
Do I have to install a programm (Twisted-13.0.0.win32-py2.7.msi (md5) ) or zope.interface-3.6.0.win-amd64-py2.6.exe (md5) ) inside the path
QGIS Brighton\apps\Python27\Lib\site-packages\twisted\  or
QGIS Brighton\apps\Python27\Lib\site-packages\zope\
or do I habe to copy only packages (which one?) inside the mentioned paths?

Thank you!

JM

**Comment by rgisset** [comment]
> or do I have to copy only packages (which one?) inside the mentioned paths?
> 
> This one  :)

Regards

Roberto

**Comment by QGIS-user** [comment]
Hi Roberto

I am not an expert in Python. 

Still I do not know what kind of file I have to copy. There are so many!

Best regards

JM

Von: rgisset [mailto:notifications@github.com] 
Gesendet: Freitag, 20. Februar 2015 13:48
An: geodrinx/gearthview
Cc: QGIS-user
Betreff: Re: [gearthview] No module named zope.interface (#1)

> or do I have to copy only packages (which one?) inside the mentioned paths?
> 
> This one :)

Regards

Roberto

**Comment by geodrinx** [comment]
Jean-Marie,

You need to copy all two folders "zope" and "twisted"  with all contains (and with subfolders)  under  Apps/Python of QGIS. 

Regards

Roberto

**Comment by sylar11** [comment]
Hi all,
These are the files I installed:

zope.interface-3.8.0.win-amd64-py2.7.exe
Twisted-15.0.0.win-amd64-py2.7.exe

I Installed both of them but I still have the same error

I have python 2.7 installed
I’m using QGIS Brighton 2.6.1 on a WINDOWS 7 ENTERPRISE 64 bit machine
but I tried also with QGIS Wien just released

Is there the possibility to describe step by step what has to be done to let them work?

thanks in advance 

Regards,

Bart

**Comment by QGIS-user** [comment]
Hi sylar11
I have done the same experience than you and still I don't have any solution!
I think because you have installed python 2.7 separately (I have also done it) and because QGIS use his internally installed python, always if zope and twisted are installed zope and twisted are placed in python 2.7 installed separately and not in the internal QGIS-Python version.
But also I don't now how to install zope and twisted inside QGIS in Python. 
I also wish a qualified support for this problem.
Regards, JM

**Comment by QGIS-user** [comment]
Hi sylar11 (again)
For the moment I deinstalled gearthview 2.0.2 and installed version 1.0.7. This version is working whitout zope and twisted.
JM

**Comment by sylar11** [comment]
Hi JM,
where can I find this previous version of GE view plugin?

Or is there someone able to explain how to install these lib under the QGIS \apps\Python27\Lib\site-packages\ folder??

**Comment by geodrinx** [comment]
Hello all,

please look at this:

http://exporttocanoma.blogspot.it/2015/01/gearthview-20-plugin-per-qgis.html

Simply, you need to download these ZIP:

https://drive.google.com/file/d/0B61MnFr3hr6menJCUDM0b01TNzg/view?usp=sharing
https://drive.google.com/file/d/0B61MnFr3hr6mcUhoNlJ6bzQxMHc/view?usp=sharing

unzip them inside your :

c:\Users\YOURUSER\Programmi\QGIS
YOURVERSION\apps\Python27\Lib\site-packages\

And you need to restart QGIS.

BTW, if you want the old version, here you can find it:

https://plugins.qgis.org/plugins/gearthview/version/1.0.7/

Regards

Roberto

2015-03-03 10:14 GMT+01:00 sylar11 notifications@github.com:

**Comment by QGIS-user** [comment]
Hi Bart
The old version can be found at - http://plugins.qgis.org/plugins/gearthview/ - , then go to "Versions"

The zipped file-container GEarthView 1.0.7 must be downloaded, unzipped and placed completely in C:\Users\JM.qgis2\python\plugins
Best regards
JM

**Comment by sylar11** [comment]
Hi Roberto,
thanks for your answer.
I tried your suggestions but it did not work unfortunately.

I still get the same error
do you have any other ideas to solve this problem? or perhaps we could go deeper for solving it

Regards

Bartolomeo

**Comment by sylar11** [comment]
Hi JM,
if I put the unzipped folder in the path you indicated I have this error

This plugin is broken
Missing metadata file

do you have the same problem?

thanks 

Bartolomeo

**Comment by QGIS-user** [comment]
Hi Bartolomeo
No, the version 1.0.7 works perfectly. The unzipped folder (gearthview) must be placed in 
C:\Users\your_account.qgis2\python\plugins\ , after that you will have the new folder:
C:\Users\your_account.qgis2\python\plugins\gearthview
"your_account" is the name you logged in in your computer! For me it is "Jean-Marie"
Inside the new folder gearthview they are (after installation):
3 folders (help, i18n, temp) and
20 files (upload the picture .png and you will see the name of all files)
![gearthview](https://cloud.githubusercontent.com/assets/11088136/6460849/0f5fb5ac-c19b-11e4-8e34-1e3400b8a41c.PNG)

Regards, Jean-Marie

**Comment by geodrinx** [comment]
You need to unzip the folder. 

Inviato da iPhone

Il giorno 03/mar/2015, alle ore 10:54, sylar11 notifications@github.com ha scritto:

**Comment by sylar11** [comment]
Hi JM,
now i got what I was doing wrong. Once the folder is unzipped it is necessary to put in the path 
C:\Users\your_account.qgis2\python\plugins\

only the folder "gearthview" and not directly the output of the unzipped process: "gearthview-1.0.7" folder otherwise it is not able to restore the plugin.

Of course it is important to not do any update of the plugin otherwise it will not work again.

thanks for your suggestions and support!!
I hope that I will be able to use the latest version of the gearthview plugin as soon as possible.

Regards,
Bartolomeo

**Comment by sylar11** [comment]
Hi Roberto,
I put the unzipped folder in the path you indicated  but it is not working..

**Comment by geodrinx** [comment]
Bartolomeo,

To have GEarthView 2  working,  if you have Windows 7,
you need to insert both folders (zope  and  twisted) with all contents under your

c:\Users\YOURUSER\Programmi\QGIS YOURVERSION\apps\Python27\Lib\site-packages\

and you need to restart QGIS.

Do you have done exactly  this ?

Tell me

Regards

Roberto

**Comment by QGIS-user** [comment]
Hello
Success! For the first time GEarthView 2.0.1 is working. But the installation way (for Windows 8.1 !) was different as Roberto eyplained.

a) download these ZIP: 
https://drive.google.com/file/d/0B61MnFr3hr6menJCUDM0b01TNzg/view?usp=sharing and
https://drive.google.com/file/d/0B61MnFr3hr6mcUhoNlJ6bzQxMHc/view?usp=sharing
b)  Unzip the two ZIP-folders. Inside the unzipped folders, you will find two folders:
_MACOSX and twisted  or
_MACOSX and zope
Use only those two folders "twisted" and "zope" found inside the ZIP-folders!
c) the (unzipped!) folders "zope" and "twisted" are copied in C:\Program Files\QGIS Wien\apps\Python27\Lib\site-packages
![installation_zope and twisted](https://cloud.githubusercontent.com/assets/11088136/6469820/da904356-c1df-11e4-939b-2ddee4a6dbad.png)

d) Start QGIS
e) Install the new Version GEarthView 2.0.1
f) Test everithing

Best regards

Jean-Marie

**Comment by rgisset** [comment]
> Success! For the first time GEarthView 2.0.1 is working.
> 
> :)

Good work with it. 
For example, now you can search a place with google earth and move qgis view on it.

Remember, the first time GEarthView only starts google earth.  To view the published image on GE, you need to repeat the call. 

Regards

Roberto (GEarthView author)

**Comment by sylar11** [comment]
Hi Roberto and JM,
this solution works fine for me too!! That's great!

The problem was similar to the one that I already put in evidence about the folder to be inserted in the 
C:\Users\your_account.qgis2\python\plugins\    where 

only the "gearthview" folder has to be put there

thanks to all of us for having solved this problem!

have a nice day!!

ciao

Bart

**Comment by flink13** [comment]
hello everyone I've followed the instructions to install zope and twisted,, but I had a problem like this, " 'module' object no attribute 'reactor already install error'. 
please help,,

**Comment by geodrinx** [comment]
Simply, restart QGIS

Inviato da iPhone

Il giorno 12/mag/2015, alle ore 05:37, flink13 notifications@github.com ha scritto:

**Comment by flink13** [comment]
thanks,, finaly it works ,,

**Comment by Kapanther** [comment]
Will add that if you installed using OSGEO installer. you will need to place in the PYTHON27 folder in there

C:\OSGeo4W64\apps\Python27\Lib\site-packages

or

C:\OSGeo4W\apps\Python27\Lib\site-packages

Thanks heaps worked on WINDOWS 7 as well

Thanks

**Comment by sylar11** [comment]
Hi all,
today I installed QGIS 2.12.3 Lyon and I faced again the same problem.
Even if I followed the suggestion we found: 
1. copy the (unzipped!) folders "zope" and "twisted" are copied in C:\Program Files\QGIS Wien\apps\Python27\Lib\site-packages 
2. copy the folder "gearthview" in the path
   C:\Users\your_account.qgis2\python\plugins\ 

In this case I had to copy the following file
zope.interface-4.1.2-py2.7-nspkg.pth
in the folder 
C:\OSGeo4W64\apps\Python27\Lib\site-packages

Hope this helps.

But the way, why all this steps are not integrating in the installation process!?!?

**Comment by geodrinx** [comment]
As you can read here:
http://plugins.qgis.org/plugins/gearthview/

You can download newer versions from the Github "Code repository" (link below) and use the "Download ZIP" button. Then, unzip the contains of the ZIP under your folder:
/.qgis2/python/plugins/gearthview-master/
Then rename "gearthview-master" as "gearthview"

I never will insert new versions from "official" QuantumGIS plugin repository.

**Comment by geodrinx** [comment]
This is repository link:

https://github.com/geodrinx/gearthview

**Comment by rgisset** [comment]
Hey,

I just signed the petition "Mario Draghi: Aspettativa di vita ed età
pensionabile" and wanted to see if you could help by adding your name.

Our goal is to reach 100 signatures and we need more support. You can read
more and sign the petition here:

http://chng.it/VwkLxwZ94Q

Thanks!
Ro
