### ISSUE TITLE
Docs and sample data in a more appropriate location

### ISSUE THREAD

**Issue by pcav** [geodrinx/gearthview#11]
They are currently placed unter temp; a more standard dir would be docs, or data.
Thanks.

**Comment by geodrinx** [comment]
what do you intend with "Docs and sample data"  ?
I have only temporary file inside "temp".
Perhaps, you mislead by a "doc.qml" file inside "temp",  but it is NOT an example document,  but it is needed to my temporary "doc.kml"  I will write during GEarthView running.

So, problem closed

**Comment by pcav** [comment]
temp does not belong to the plugin. please remove it from the repo.
thanks.

**Comment by geodrinx** [comment]
>  "temp does not belong to the plugin"
What do you mean ?  
I write inside my ".qgis2/python/plugins/gearthview/temp/"  folder.
For what reason  I should need to "please remove it from the repo"  ?
I am the programmer, and I decide what I do, when needed.
Or not ?
:)

**Comment by geodrinx** [comment]
done

**Comment by pcav** [comment]
My suggestion was aimed at a predictable directory structure, to promote collaboration around your useful and interesting work.
