### ISSUE TITLE
Plans for QGIS 3.2.X?

### ISSUE THREAD

**Issue by Crghilardi** [geodrinx/gearthview#17]
Hello, 

I wanted to open an issue asking what the status/plan for the plugin is now that the full 3.2.0 release is out. 
I am not sure how much change is needed to accommodate the new major version. I would be willing to help, although I have limited Qt experience.

**Comment by mysiar** [comment]
bump up, version 3.6 already

**Comment by geodrinx** [comment]
Hello All,
really I just have a GEarthView version for QGIS 3.x
When "it" will change the QGIS management, I will release.
Sorry, but for now it is only for me (and, of course, my beta testers :)
@presto
Roberto

**Comment by Crghilardi** [comment]
OK, thank you for the response.
