### ISSUE TITLE
Reactor already installed

### ISSUE THREAD

**Issue by MJWenm** [geodrinx/gearthview#3]
I've installed and used this plugin with previous versions of QGIS. After updating to QGIS 2.8.1. I get the following error:

"This plugin is broken 'module' object has no attribute 'ReactorAlreadyInstalledError'"

Any help would be greatly appreciated.

Thanks

**Comment by geodrinx** [comment]
Simply, restart QGIS

**Comment by MJWenm** [comment]
Thanks for the quick response.

I tried restarting QGIS and rebooting my PC - still no luck.

I'm trying a fresh install on another PC and will let you know what happens.

P.S. Thanks for a great plugin, it's a very useful tool

**Comment by MJWenm** [comment]
No luck. Best if you link me the exact zope, twisted and any other plugins / updates required.

Thanks

**Comment by geodrinx** [comment]
in this post of my blog there are indications :

http://exporttocanoma.blogspot.it/2015/01/gearthview-20-plugin-per-qgis.html

However, substantially you must copy the contents of these two zip:

https://drive.google.com/file/d/0B61MnFr3hr6menJCUDM0b01TNzg/view?usp=sharing

https://drive.google.com/file/d/0B61MnFr3hr6mcUhoNlJ6bzQxMHc/view?usp=sharing

in the directory of QGIS:

QGIS <version>\apps\Python27\Lib\site-packages\

You will have these two directories :

twisted\
zope\

**Comment by FrankOrtmann** [comment]
How do I resolve this for a Mac using MacPorts?

QGis 2.8.2
Python 2.7.9
py27-zopeinterface @4.1.1_0
py27-twisted @13.2.0_0

**Comment by geodrinx** [comment]
Simply, restart QGIS

Inviato da iPhone

Il giorno 19/mag/2015, alle ore 14:50, Frank Ortmann notifications@github.com ha scritto:

**Comment by FrankOrtmann** [comment]
I have restarted many times since I first installed (and reading the messages above) and keep getting the same issue.

**Comment by geodrinx** [comment]
Do you installed Twisted and Zope libraries ?
What OperatingSystem do you have ?  Mac, Linux or Windows ?

BTW,  in this post of my blog there are indications :

http://exporttocanoma.blogspot.it/2015/01/gearthview-20-plugin-per-qgis.html

However, substantially you must copy the contents of these two zip:

https://drive.google.com/file/d/0B61MnFr3hr6menJCUDM0b01TNzg/view?usp=sharing

https://drive.google.com/file/d/0B61MnFr3hr6mcUhoNlJ6bzQxMHc/view?usp=sharing

in the directory of QGIS:

QGIS \apps\Python27\Lib\site-packages\

You will have these two directories :

twisted\
zope\
