### ISSUE TITLE
Instalation of twisted package don't work for 64-bits QGIS

### ISSUE THREAD

**Issue by jonnyforestGIS** [geodrinx/gearthview#7]
Hi,
The installation of the zope (through easy_install) is OK for the 4 following tests.

i've do the following tests for package twisted:
QGIS 2.10.1 Pisa (Windows 7, 64bits - Standalone): error: Setup script exited with error: Unable to find vcvarsall.bat
QGIS 2.10.1 Pisa (Windows 7, 64bits - OSGeo4W): error: Setup script exited with error: Unable to find vcvarsall.bat

QGIS 2.10.1 Pisa (Windows 7, 32bits - OSGeo4W): OK

QGIS 2.10.1 Pisa (Linux Mint Rebecca, 64bits): OK

**Comment by geodrinx** [comment]
Do you installed Twisted and Zope libraries ?
What OperatingSystem do you have ? Mac, Linux or Windows ?

BTW, in this post of my blog there are indications :

http://exporttocanoma.blogspot.it/2015/01/gearthview-20-plugin-per-qgis.html

However, substantially you must copy the contents of these two zip:

https://drive.google.com/file/d/0B61MnFr3hr6menJCUDM0b01TNzg/view?usp=sharing

https://drive.google.com/file/d/0B61MnFr3hr6mcUhoNlJ6bzQxMHc/view?usp=sharing

in the directory of QGIS:

QGIS \apps\Python27\Lib\site-packages\

You will have these two directories :

twisted\
zope\

**Comment by jonnyforestGIS** [comment]
The installation through easy_install for zope works well, in the SO that i test. as I said earlier in my first comment i test in Windows 7 64 bits and Linux Mint 64 bits. In the case of Windows 7 i test the standalone 64-bits, OSGeo4W 64-bits and OSGeo4W 32-bits. 

For Linux Mint 64-bits with QGIS PISA 2.10.1 and OSGeo4W 32-bits (install through command line with easy_install the twisted 15.4.0 and zope.interface 3.8.0 packages) works fine.

Note: the package that you share, twisted 13.0.0 is different of the python repository (twisted 15.4.0). And is this package that give the error in the instalation of plugin: error: Setup script exited with error: Unable to find vcvarsall.bat

So i install manually the folder with twisted 13.0.0 and works for the others versions. I think the problem is the the package of python repository for twisted 15.4.0 in Windows 7 64-bits architecture.

Thanks and regards
João
