### ISSUE TITLE
installation instructions?

### ISSUE THREAD

**Issue by dschneiderch** [geodrinx/gearthview#8]
could someone provide instructions for installing this plugin since the repo version is outdated?
Thanks

**Comment by geodrinx** [comment]
I updated the description of plugin in official repository, inserting the install instruction, that are these:

You can download newer versions from the Github "Code repository" (link below) and use the "Download ZIP" button. Then, unzip the contains of the ZIP under your folder:
/.qgis2/python/plugins/gearthview-master/
Then rename "gearthview-master" as "gearthview"

Good work with gearthview plugin !

**Comment by geodrinx** [comment]
Here, the link to github Code repository:

https://github.com/geodrinx/gearthview

and this is the direct link to the plugin ZIP:

https://github.com/geodrinx/gearthview/archive/master.zip
